<?php

return [
    "name" => "Name",
    "branch" => "Branch",
    "attendance" => "Attendance",
    "attendance_status" => "Attendance Status",
    "department" => "Department",
    "employee" => "Employee",
    "job_position" => "Job Position",
    "payroll" => "Payroll",
    "training" => "Training",
    "date" => "Date",
    "from_date" => "From Date",
    "to_date" => "To Date",
    "attendance_status" => "Attendance Status",
    "is_generated" => "Is Generated",
    "created_by" => "Created By",
    "generated_by" => "Generated By",
    "attendance_generator" => "Attendance Generator",
];
