version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel_app
        container_name: laravel_app
        volumes:
            - .:/var/www/html
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
            - ./.env:/var/www/html/.env
            - ./storage:/var/www/html/storage
        expose:
            - "9000"
        environment:
            - APP_ENV=${APP_ENV}
            - APP_URL=${APP_URL}
            - APP_DEBUG=${APP_DEBUG}
            - APP_KEY=${APP_KEY}
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
        networks:
            - app-net

    nginx:
        image: nginx:latest
        container_name: laravel_nginx
        volumes:
            - .:/var/www/html
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8001:80"
        depends_on:
            - app
        networks:
            - app-net
networks:
    app-net:
        external: true
        name: app-network
