version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel_app
        container_name: laravel_app
        restart: unless-stopped
        volumes:
            - .:/var/www/html
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
            - ./.env:/var/www/html/.env
            - ./storage:/var/www/html/storage
        expose:
            - "9000"
        environment:
            - APP_ENV=${APP_ENV}
            - APP_URL=${APP_URL}
            - APP_DEBUG=${APP_DEBUG}
            - APP_KEY=${APP_KEY}
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
        networks:
            - app-net

    # Queue Worker Service
    laravel-queue-worker:
        image: laravel_app # Reference the existing image built for laravel-app
        container_name: laravel-queue-worker
        tty: true
        environment:
            SERVICE_NAME: laravel-queue-worker
            SERVICE_TAGS: dev
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - app-net
        command: php artisan queue:work --queue=default --sleep=3 --tries=3 --max-time=3600
        restart: always

    # Scheduler Service
    laravel-scheduler-worker:
        image: laravel_app # Reference the existing image built for laravel-app
        container_name: laravel-scheduler-worker
        tty: true
        environment:
            SERVICE_NAME: laravel-scheduler-worker
            SERVICE_TAGS: dev
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - app-net
        command: php artisan schedule:work
        restart: always

    nginx:
        image: nginx:latest
        container_name: laravel_nginx
        restart: unless-stopped
        volumes:
            - .:/var/www/html
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8003:80"
        depends_on:
            - app
        networks:
            - app-net
networks:
    app-net:
        external: true
        name: app-network
